# Generated by Django 6.0.5 on 2026-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OriginalURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("shortened", models.IntegerField(default=1, editable=False)),
                ("url_hash", models.CharField(default="", max_length=200)),
                ("short_url", models.URLField(default="", max_length=2048)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("visited", models.IntegerField(default=0)),
            ],
        ),
    ]
